CREATE TYPE "SexoAluno" AS ENUM ('MASCULINO', 'FEMININO');

ALTER TABLE "Aluno"
ADD COLUMN "sexo" "SexoAluno" NOT NULL DEFAULT 'MASCULINO',
ADD COLUMN "fotoUrl" TEXT,
ADD COLUMN "fotoPublicId" TEXT,
ADD COLUMN "dataNascimento" TIMESTAMP(3),
ADD COLUMN "dataBatismo" TIMESTAMP(3),
ADD COLUMN "endereco" TEXT,
ADD COLUMN "email" TEXT,
ADD COLUMN "whatsapp" TEXT NOT NULL DEFAULT '';
